// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClGex0x-kSPuo_qtHCc5h-3oHJiXmiQDQ',
    appId: '1:567137535061:web:8bc37e204e34f740db40dc',
    messagingSenderId: '567137535061',
    projectId: 'travelappapi-d6ef4',
    authDomain: 'travelappapi-d6ef4.firebaseapp.com',
    databaseURL: 'https://travelappapi-d6ef4-default-rtdb.firebaseio.com',
    storageBucket: 'travelappapi-d6ef4.appspot.com',
    measurementId: 'G-VL540MBWKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5hsSUdXUlhWaEeDA6youzu1Kt2fJAhlo',
    appId: '1:567137535061:android:dd076dc40089fb56db40dc',
    messagingSenderId: '567137535061',
    projectId: 'travelappapi-d6ef4',
    databaseURL: 'https://travelappapi-d6ef4-default-rtdb.firebaseio.com',
    storageBucket: 'travelappapi-d6ef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwLBq_dFlagfq0vx16sLeQHWqxs8qXoW0',
    appId: '1:567137535061:ios:2038987a9ba5b1b4db40dc',
    messagingSenderId: '567137535061',
    projectId: 'travelappapi-d6ef4',
    databaseURL: 'https://travelappapi-d6ef4-default-rtdb.firebaseio.com',
    storageBucket: 'travelappapi-d6ef4.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwLBq_dFlagfq0vx16sLeQHWqxs8qXoW0',
    appId: '1:567137535061:ios:703b65ccbf7af2d3db40dc',
    messagingSenderId: '567137535061',
    projectId: 'travelappapi-d6ef4',
    databaseURL: 'https://travelappapi-d6ef4-default-rtdb.firebaseio.com',
    storageBucket: 'travelappapi-d6ef4.appspot.com',
    iosBundleId: 'com.example.travelApp.RunnerTests',
  );
}
