name: travel_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  bloc:
  flutter_bloc: ^8.1.3
  equatable:
  http:
  webview_flutter: ^4.4.1

  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.22.0
  google_fonts: ^6.1.0
  firebase_auth: ^4.14.0
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.5
  flutter_local_notifications: ^16.1.0
  appwrite: ^11.0.1
  image_picker: ^1.0.4
  uuid: ^4.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - img/
